#ifndef LEAP_GATEWAY_EIP_CONF_H_
#define LEAP_GATEWAY_EIP_CONF_H_

/* Single source of truth for EtherNet/IP I/O assembly sizes on this gateway. */
#define LEAP_GATEWAY_INPUT_ASSEMBLY_NUM   100U
#define LEAP_GATEWAY_OUTPUT_ASSEMBLY_NUM  150U
#define LEAP_GATEWAY_CONFIG_ASSEMBLY_NUM   151U
#define LEAP_GATEWAY_HEARTBEAT_INPUT_ONLY_ASSEMBLY_NUM  152U
#define LEAP_GATEWAY_HEARTBEAT_LISTEN_ONLY_ASSEMBLY_NUM 153U
#define LEAP_GATEWAY_EXPLICIT_ASSEMBLY_NUM  154U
#define LEAP_GATEWAY_IO_ASSEMBLY_BYTES      64U

#endif /* LEAP_GATEWAY_EIP_CONF_H_ */
