#ifndef OPENER_APP_IDENTITY_CONF_H_
#define OPENER_APP_IDENTITY_CONF_H_

#define OPENER_APP_IDENTITY_VENDOR_ID 1U
#define OPENER_APP_IDENTITY_DEVICE_TYPE 12U
#define OPENER_APP_IDENTITY_PRODUCT_CODE 65001U
#define OPENER_APP_IDENTITY_MAJOR_REVISION 1U
#define OPENER_APP_IDENTITY_MINOR_REVISION 0U
#define OPENER_APP_IDENTITY_PRODUCT_NAME "LEAP-Gateway"

#endif /* OPENER_APP_IDENTITY_CONF_H_ */
