#ifndef OPENER_USER_CONF_H_
#define OPENER_USER_CONF_H_

#define OPENER_NUMBER_OF_SUPPORTED_SESSIONS 20
#define OPENER_CIP_NUM_APPLICATION_SPECIFIC_CONNECTABLE_OBJECTS 1
#define OPENER_CIP_NUM_EXPLICIT_CONNECTABLE_OBJECTS 6
#define OPENER_TCPIP_IFACE_CFG_SETTABLE 1
#define OPENER_ETHLINK_LABEL_ENABLE 1
#define OPENER_ETHLINK_CNTRS_ENABLE 1

#define kOpenerTimerTickInMilliSeconds 10

#endif /* OPENER_USER_CONF_H_ */
