#!/usr/bin/env bash
# Generate leap_build_info_gen.h for RTEMS waf builds (no CMake required).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
REPO="$(cd "$ROOT/../../../.." && pwd)"
OUT="$ROOT/generated/leap_build_info_gen.h"

GIT="unknown"
if command -v git >/dev/null 2>&1 && [[ -d "$REPO/.git" ]]; then
    GIT="$(git -C "$REPO" rev-parse --short HEAD 2>/dev/null || echo unknown)"
fi

DATE="$(date -u +"%Y-%m-%d UTC")"

mkdir -p "$ROOT/generated"
cat >"$OUT" <<EOF
/*
 * leap_build_info_gen.h (generated by scripts/gen_build_info.sh)
 *
 * Copyright (c) 2026 Adam G. Sweeney <agsweeney@gmail.com>
 * SPDX-License-Identifier: MIT
 */

#ifndef LEAP_BUILD_INFO_GEN_H
#define LEAP_BUILD_INFO_GEN_H

#define LEAP_BUILD_GIT  "$GIT"
#define LEAP_BUILD_DATE "$DATE"

#endif /* LEAP_BUILD_INFO_GEN_H */
EOF

echo "Wrote $OUT (git=$GIT date=$DATE)"
