# Generate leap_build_info_gen.h for RTEMS waf builds (no CMake required).
$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $PSScriptRoot
$Repo = Resolve-Path (Join-Path $Root "..\..\..\..")
$OutDir = Join-Path $Root "generated"
$Out = Join-Path $OutDir "leap_build_info_gen.h"

$Git = "unknown"
if (Get-Command git -ErrorAction SilentlyContinue) {
    Push-Location $Repo
    try {
        $GitOut = git rev-parse --short HEAD 2>$null
        if ($LASTEXITCODE -eq 0 -and $GitOut) { $Git = $GitOut }
    } finally {
        Pop-Location
    }
}

$Date = (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd") + " UTC"

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null

@(
    "/*",
    " * leap_build_info_gen.h (generated by scripts/gen_build_info.ps1)",
    " *",
    " * Copyright (c) 2026 Adam G. Sweeney <agsweeney@gmail.com>",
    " * SPDX-License-Identifier: MIT",
    " */",
    "",
    "#ifndef LEAP_BUILD_INFO_GEN_H",
    "#define LEAP_BUILD_INFO_GEN_H",
    "",
    "#define LEAP_BUILD_GIT  `"$Git`"",
    "#define LEAP_BUILD_DATE `"$Date`"",
    "",
    "#endif /* LEAP_BUILD_INFO_GEN_H */",
    ""
) | Set-Content -Encoding UTF8 $Out

Write-Host "Wrote $Out (git=$Git date=$Date)"
