macro(opener_platform_spec)
  include_directories(${PORTS_SRC_DIR}/${OpENer_PLATFORM} ${PORTS_SRC_DIR}/${OpENer_PLATFORM}/sample_application)
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -std=c99 -fcommon")
  add_definitions(-D_POSIX_C_SOURCE=200112L -D_GNU_SOURCE -DOPENER_POSIX)
  add_definitions(-DRESTRICT=restrict)
endmacro(opener_platform_spec)
